### ISSUE TITLE
Incorrect links to documentation

### ISSUE THREAD

**Issue by oadaeh** [backdrop-contrib/coder_review#8]
For the notices that include references to documentation, an incorrect domain name is used. The one that is used (backdrop.org) is for a BDSM site.
Also, the specific references are for drupal.org nodes, not backdropcms.org nodes, so just changing the domain name is not enough.

**Comment by robertgarrigos** [comment]
This has been (partially) fixed with a commit on 8 Feb 2018, but there has not been a new release since then.

**Comment by robertgarrigos** [comment]
Sorry, I pushed a commit instead of doing a PR on a new branch. I'll do a push to go back and the a new branch for a PR

**Comment by robertgarrigos** [comment]
Added a PR (https://github.com/backdrop-contrib/coder_review/pull/13) which fixes partially this. There was already a commit which fixed the links to api.backdropcms.org
